name: Python Flask CI/CD

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest  # Replace with your test command

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install SSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
    - name: Deploy to remote server
      env:
        SSH_PASS: ${{ secrets.REMOTE_SSH_PASS }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
      run: |
        sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP -p $PORT << 'ENDSSH'
          sudo systemctl stop app.service 
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl start app.service
        ENDSSH
