name: Python Flask CI/CD

on:
  push:
    branches: [ test, main, dev ] 
  pull_request:
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest 

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to remote server and fetch latest app version
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          eval "$(ssh-agent -s)"

          mkdir ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d | tr -d '\r' | ssh-add -
          ssh-keyscan -p $REMOTE_PORT $SERVER_IP >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP -p $REMOTE_PORT << 'ENDSSH'
            sudo systemctl stop app.service
            cd /home/root/task8/opi8
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl start app.service
          ENDSSH

