name: Python Flask CI/CD

on:
  push:
    branches: [ test, main, dev ] 
  pull_request:
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest 

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v2

      - name: Start SSH agent
        run: |
          # eval "$(ssh-agent -s)"
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          # ssh-add -L
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa

      - name: Debug SSH
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP -p $REMOTE_PORT exit
          
      - name: Add SSH server to known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $REMOTE_PORT $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to remote server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP -p $REMOTE_PORT << 'ENDSSH'
            sudo systemctl stop app.service 
            cd /home/root/task8/opi8
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl start app.service
          ENDSSH

